### PR TITLE
WIP: Upgrade to Godot 3.4.4 and SDK 30

### PR DESCRIPTION
**Pull request by Funmungus**
WIP  
1. We are still working on manual testing, README updates, and demo updates.
2. Request help testing Interstitial and RewardedAd.

config.gradle: Copied from Android build template. Find a way to
automate.
Interstitial+RewardedVideo+GodotRewardedVideo: Implement changed
requirements for Interstitial and Rewarded Ads.
GodotAdMob+admob.gd: Remove signals that are no longer available.  Add
support for new clicked and impression signals.
Upgrade Gradle to 7.2
build.gradle+GodotAdMob.gdap: Upgrade GMS to 21.0.0
More package upgrades

Related issues: #189 #192 #168 #186

### CODE REVIEW

**Comment by Shin-NiL** [comment]
Thank you, I'll merge as soon as it is done :)

**Comment by Funmungus** [comment]
@Shin-NiL Everything is ready for review. The last commit brings back the interstitial and video opened signals.  I did not test the changes in the last commit.

**Comment by Shin-NiL** [comment]
This is a huge update, thank you very much.
I'll merge it as is and then we need to do some tests before the release.
Thank you again.

**Comment by Funmungus** [comment]
My pleasure.

**Pull request merged**
